name = "sds"
main = "src/worker.js"
compatibility_date = "2024-07-06"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "wikipedia-fetcher"

[env.staging]
name = "wikipedia-fetcher-staging"
